version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000" # optional for local debugging
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
