name: earth-forum
services:
- name: backend
  source_dir: backend
  dockerfile_path: backend/Dockerfile
  github:
    repo: Hadroon/earth-forum
    branch: add-folder-str
    deploy_on_push: true
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production

- name: frontend
  source_dir: frontend
  dockerfile_path: frontend/Dockerfile
  github:
    repo: Hadroon/earth-forum
    branch: add-folder-str
    deploy_on_push: true
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
